import"./assets/styles-JE8YjOlG.js";import{i as a,a as n}from"./assets/vendor-4yCzdkXl.js";function v(t,o,e){t.forEach(c=>{c.classList.remove(e)}),o.classList.add(e)}function _(t,o="success"){const e={message:t,position:"topRight",timeout:5e3};switch(o){case"success":a.success(e);break;case"error":a.error(e);break;case"warning":a.warning(e);break;case"info":a.info(e);break;default:a.error({message:"Invalid type of tost",position:"topRight",timeout:5e3})}}const s={categoriesList:document.querySelector(".categories"),productsList:document.querySelector(".products"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalCloseBtn:document.querySelector(".modal__close-btn"),modalProduct:document.querySelector(".modal-product"),searchForm:document.querySelector(".search-form")};function w(){s.modal.classList.add("modal--is-open"),document.body.style.overflow="hidden",window.addEventListener("keydown",g),s.modalCloseBtn.addEventListener("click",d),s.modal.addEventListener("click",f)}function d(){s.modal.classList.remove("modal--is-open"),document.body.style.overflow="",window.removeEventListener("keydown",g),s.modalCloseBtn.removeEventListener("click",d),s.modal.removeEventListener("click",f)}function g(t){t.code==="Escape"&&d()}function f(t){t.currentTarget===t.target&&d()}const P="https://dummyjson.com",i={CATEGORIES:"/products/category-list",PRODUCTS:"/products",PRODUCTS_BY_CATEGORY:"/products/category/",PRODUCT_BY_ID:"/products/",SEARCH:"/products/search"};n.defaults.baseURL=P;async function y(){const{data:t}=await n(i.PRODUCTS);return t}async function E(){const{data:t}=await n(i.CATEGORIES);return t}async function S(t){const{data:o}=await n(`${i.PRODUCTS_BY_CATEGORY}${t}`);return o}async function T(t){const{data:o}=await n(`${i.PRODUCT_BY_ID}${t}`);return o}async function k(t){const{data:o}=await n(`${i.SEARCH}?q=${t}`);return o}function R(t){const e=["All",...t].map(r=>`<li class="categories__item">
  <button class="categories__btn" type="button">${r}</button>
</li>
`).join("");s.categoriesList.innerHTML=e,document.querySelector(".categories__btn").classList.add("categories__btn--active")}function m(t){const o=t.map(({id:e,thumbnail:c,title:r,category:u,brand:l,price:p})=>`<li class="products__item" data-id="${e}">
    <img class="products__image" src="${c}" alt="${r}"/>
    <p class="products__title">${r}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${l}</span></p>
    <p class="products__category">Category: ${u}</p>
    <p class="products__price">Price: ${p}$</p>
 </li>`).join("");s.productsList.insertAdjacentHTML("beforeend",o)}function L(){s.productsList.innerHTML=""}function b(){s.notFound.classList.add("not-found--visible")}function h(){s.notFound.classList.remove("not-found--visible")}function A({images:t,title:o,description:e,shippingInformation:c,price:r,returnPolicy:u,tags:l}){const p=l.map(C=>`<li>${C}</li>`).join(""),$=`<img class="modal-product__img" src="${t[0]}" alt="${o}" />

<div class="modal-product__content"> <p class="modal-product__title">${o}</p>
<ul class="modal-product__tags">${p}</ul> <p class="modal-product__description">${e}</p>
<p class="modal-product__shipping-information">Shipping: ${c}</p>
<p class="modal-product__return-policy">Return Policy: ${u}</p>
<p class="modal-product__price">Price: ${r}$</p>
<button class="modal-product__buy-btn" type="button">Buy</button> </div>`;s.modalProduct.innerHTML=$}async function B(t){try{const o=await E();R(o);const{products:e}=await y();m(e)}catch(o){console.error(`Помилка ініціанілізації сторінки Home ${o}`)}}async function O(t){if(t.target.nodeName==="BUTTON"){L();try{const o=t.target.textContent,e=document.querySelectorAll(".categories__btn");v(e,t.target,"categories__btn--active");let c;o==="All"?c=await y():c=await S(o),c.products.length>0?(h(),m(c.products)):b()}catch(o){console.log(`Помилка отримання продуктів по категорії ${o}`)}}}async function q(t){const o=t.target.closest(".products__item");if(!o)return;const e=o.dataset.id,c=await T(e);console.log(c),A(c),w()}async function D(t){t.preventDefault();const o=t.currentTarget.elements.searchValue.value.trim();if(!o){_("Please enter a valid search query","warning");return}L();try{const{products:e}=await k(o);e.length>0?(m(e),h()):b()}catch{_(`Помилка отримання продуктів по пошуку ${err}`,"error"),console.log(`Помилка отримання продуктів по пошуку ${err}`)}}document.addEventListener("DOMContentLoaded",B);s.categoriesList.addEventListener("click",O);s.productsList.addEventListener("click",q);s.searchForm.addEventListener("submit",D);
//# sourceMappingURL=index.js.map
